production:
  secret_key_base: static_production_secret_key

development:
  secret_key_base: static_secret_key

test:
  secret_key_base: static_test_secret_key


secret_key_base: global_key_for_all_env